### ISSUE TITLE
Interview Michael

### ISSUE THREAD

**Issue by brockwalker01** [MTM6330-F18/Final-TeamUnemployed#2]
Courses
course information/schedule
bio
contact information
picture

**Comment by aliaa22** [comment]
Here is the info from our interview with Michael - Alia & Kudzo

![michaeleisenbraun](https://user-images.githubusercontent.com/35577132/48369695-4d7ee200-e685-11e8-8e49-c96cf7241b65.jpg)

[michaelEisenbraun.txt](https://github.com/MTM6330-F18/Final-TeamUnemployed/files/2573283/michaelEisenbraun.txt)

**Comment by brockwalker01** [comment]
reviewed. all is well
