### ISSUE TITLE
Interview Robert

### ISSUE THREAD

**Issue by brockwalker01** [MTM6330-F18/Final-TeamUnemployed#3]
bio
course info
course schedule
picture
contact inforamtion

**Comment by christianarciaga** [comment]
1. I teach MTM6330 Web Production and MTM6430 Web Applications in the IMD program.  I also teach MTM9111 Fundamentals of Computer Hardware and Networking and MAD9124 Mobile API Development in the Mobile Application Design & Development program.

2. I am generally available before and after class for some quick help, but for a longer tutoring appointment,  email me at mckennr@algonquincollege.com to setup an appointment to meet in Room T313.

3. 
Full stack web developer,
Entrepreneur, and Educator
I love building frontend web applications with Vue.js and backend APIs with Laravel PHP or Node.js.

I have always been driven to find the most elegant and intuitive solution that will make someone's everyday tasks a little bit simpler.

The ever changing nature of the information technology industry provides endless fuel for my love of learning and now, as a part-time college professor, I also get the chance to share that experience and passion with my students.
