### ISSUE TITLE
Gather class schedule for all sections

### ISSUE THREAD

**Issue by brockwalker01** [MTM6330-F18/Final-TeamUnemployed#4]

**Comment by Kud20** [comment]
![schedule1](https://user-images.githubusercontent.com/17076325/48370491-83bd6100-e687-11e8-9ffc-111ffd9ded7c.jpg)
![schedule2](https://user-images.githubusercontent.com/17076325/48370494-861fbb00-e687-11e8-8c52-7d7133e05ded.jpg)
![schedule3](https://user-images.githubusercontent.com/17076325/48370499-88821500-e687-11e8-946a-a5994e52e098.jpg)

**Comment by brockwalker01** [comment]
great work kudzo
